### PR TITLE
Swith to descriptive readme headers

### PR DESCRIPTION
**Pull request by dcwalk**
Hey @patcon just thinking it might be nice to signal what the scripts are in their header?
Not too fussed wither way, but was thinking that from #11

### CODE REVIEW

**Review by patcon — APPROVED** [review]
Looks great! I think this is really helpful :)

**Comment by patcon** [comment]
Do we have a preference for the submitted merging? I've always been fuzzy on that, and should have asked :) (Nevermind how simple this one is, but with a larger one, what are your feels?)

(I'm happy to submit a PR for CONTRIBUTING.md in overview with whatever we think here)

**Comment by dcwalk** [comment]
I think we say something to the effect of Lieutenants merge? that has been
the principal I've been operating under (oop just now realizing I may have
been stepping on yr toes).

happy to formalize and specify!

**Comment by patcon** [comment]
Nope, no toe-stepping! (Wasn't sure if the concept of lieutenants was something in people's brains lately.)

**Comment by dcwalk** [comment]
We maintain and periodically update a team. Probably due for another tidy as a few have moved on from the project.

**Pull request merged**
