### PR TITLE
We fix config maybe we get build?

### PR DESCRIPTION
**Pull request by Mr0grog**
Worked on my fork ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by Mr0grog** [comment]
Yup it work

**Comment by Mr0grog** [comment]
@patcon

**Comment by Mr0grog** [comment]
Fixes #20.

**Comment by patcon** [comment]
Weird, merging seemed to kick off a build, so that seems better than before! Thanks @Mr0grog!

**Pull request merged**
