### PR TITLE
Make video uploads use the creativeCommons license

### PR DESCRIPTION
**Pull request by patcon**
Reticketed from https://github.com/edgi-govdata-archiving/edgi-scripts/pull/1#discussion_r128335181

There is a reference to a hardcoded fix through the link above. Anyone is welcome to help that along, but I'll get to it later if now.

### CODE REVIEW

**Comment by dcwalk** [comment]
not sure I'm following! What merge are you looking for? Can I help?

**Comment by patcon** [comment]
Was just saying that the linked PR needed merging, but I just forked it to the edgi or and we'll use it directly :)

**Review by dcwalk — APPROVED** [review]
This looks good to me 👍

**Pull request merged**
