### PR TITLE
Adds CoC badge per https://github.com/edgi-govdata-archiving/overview…

### PR DESCRIPTION
**Pull request by Frijol**
Adds CoC badge per https://github.com/edgi-govdata-archiving/overview/issues/207

### CODE REVIEW

**Comment by lightandluck** [comment]
Hmmm, this is breaking CircleCI build and I don't understand why

**Comment by Frijol** [comment]
Looks like it failed on Zoom API credentials (have they been updated/this build would fail on any PR?)
@Mr0grog do you know?

**Comment by Mr0grog** [comment]
Oops, sorry I didn’t see this last week. @Frijol you made your PR from a fork instead of a branch on this repo, so as a security measure, Circle won’t give you access to secret env vars.

**Comment by Frijol** [comment]
@Mr0grog does that mean this is safe to merge despite the failed check?

**Comment by Mr0grog** [comment]
Sure! More generally, it means you’re always going to have this problem, which sometimes won’t be such a non-issue, when you make a PR from a fork on this repo. (So in the future, please don’t PR to this repo from a fork.)

**Pull request merged**
