### PR TITLE
Hide sensitive output about videos/playlists

### PR DESCRIPTION
**Pull request by patcon**

### CODE REVIEW

**Comment by patcon** [comment]
Tested. Works. Now looks like this: https://imgur.com/KsHzH2l

**Review by dcwalk — APPROVED** [review]
🙏 nice!

**Comment by dcwalk** [comment]
Just re-ran the circleCI checks, not sure why they stopped before. Merging in optimistically 😊

**Comment by patcon** [comment]
Found commit where issue started:
https://circleci.com/gh/edgi-govdata-archiving/edgi-scripts/953

Seems that pip doesn't know how to handle the interactive action required, so needs to flag `-exists-action w` (for "wipe")

Making this change now

**Pull request merged**
